### ISSUE TITLE
How to get the "data-bin/multi30k.en-de.mmt_vqa/train.imgname"

### ISSUE THREAD

**Issue by Jianglllri** [libeineu/MMT-VQA#1]
Hi
Thank you for your great work. I found No such file or directory when trying to run your code: 'data-bin/multi30k.en-de.mmt_vqa/train.imgname'.I'd like to know what code was executed to generate this file?

**Comment by yuxinzuo** [comment]
Apologies for omitting a description of the source of this file.

'data-bin/multi30k.en-de.mmt_vqa/train.imgname' indicates image file name of  multi30k, you can get it from here: https://github.com/multi30k/dataset/blob/master/data/task1/image_splits/train.txt.

Note: You can post-process this file based on the paths of the Flickr images you downloaded.

**Comment by Jianglllri** [comment]
Thank you for your reply. But now I have another problem, I have no problem running English to German translation, but my English to French translation is very bad, I only changed the target language, the other hyperparameters are the same as in German, can I ask what went wrong?
Generate test with beam=5: BLEU4 = 3.32, 30.5/6.2/1.7/0.5 (BP=0.951, ratio=0.952, syslen=13553, reflen=14229)
VizSeqScore(corpus_score=0.207, sent_scores=None, group_scores=None)
